# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gambit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gambit.proto',
  package='gambit',
  syntax='proto3',
  serialized_pb=_b('\n\x0cgambit.proto\x12\x06gambit\"\x8d\x02\n\x13\x45xecuteMatchRequest\x12\x34\n\x04init\x18\x01 \x01(\x0b\x32&.gambit.ExecuteMatchRequest.ClientInit\x12\x37\n\tmake_move\x18\x02 \x01(\x0b\x32$.gambit.ExecuteMatchRequest.MakeMove\x1a_\n\nClientInit\x12(\n\x08identity\x18\x01 \x01(\x0b\x32\x16.gambit.IdentityConfig\x12\'\n\x0bgame_config\x18\x02 \x01(\x0b\x32\x12.gambit.GameConfig\x1a&\n\x08MakeMove\x12\x1a\n\x04move\x18\x01 \x01(\x0b\x32\x0c.gambit.Move\"\xc7\x01\n\x14\x45xecuteMatchResponse\x12\x43\n\x0bmatch_state\x18\x01 \x01(\x0b\x32..gambit.ExecuteMatchResponse.ExecuteMatchState\x1aj\n\x11\x45xecuteMatchState\x12\x18\n\x10seconds_in_queue\x18\x01 \x01(\r\x12\x14\n\x0c\x63urrent_move\x18\x02 \x01(\r\x12%\n\ngame_state\x18\x03 \x01(\x0b\x32\x11.gambit.GameState\"&\n\x0eIdentityConfig\x12\x14\n\x0c\x63lient_token\x18\x01 \x01(\t\"\x1d\n\nGameConfig\x12\x0f\n\x07game_id\x18\x01 \x01(\t\"\x0b\n\tGameState\"\x06\n\x04Move2^\n\x0bGameService\x12O\n\x0c\x45xecuteMatch\x12\x1b.gambit.ExecuteMatchRequest\x1a\x1c.gambit.ExecuteMatchResponse\"\x00(\x01\x30\x01\x62\x06proto3')
)




_EXECUTEMATCHREQUEST_CLIENTINIT = _descriptor.Descriptor(
  name='ClientInit',
  full_name='gambit.ExecuteMatchRequest.ClientInit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identity', full_name='gambit.ExecuteMatchRequest.ClientInit.identity', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='game_config', full_name='gambit.ExecuteMatchRequest.ClientInit.game_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=254,
)

_EXECUTEMATCHREQUEST_MAKEMOVE = _descriptor.Descriptor(
  name='MakeMove',
  full_name='gambit.ExecuteMatchRequest.MakeMove',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='move', full_name='gambit.ExecuteMatchRequest.MakeMove.move', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=294,
)

_EXECUTEMATCHREQUEST = _descriptor.Descriptor(
  name='ExecuteMatchRequest',
  full_name='gambit.ExecuteMatchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='init', full_name='gambit.ExecuteMatchRequest.init', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='make_move', full_name='gambit.ExecuteMatchRequest.make_move', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EXECUTEMATCHREQUEST_CLIENTINIT, _EXECUTEMATCHREQUEST_MAKEMOVE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=294,
)


_EXECUTEMATCHRESPONSE_EXECUTEMATCHSTATE = _descriptor.Descriptor(
  name='ExecuteMatchState',
  full_name='gambit.ExecuteMatchResponse.ExecuteMatchState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds_in_queue', full_name='gambit.ExecuteMatchResponse.ExecuteMatchState.seconds_in_queue', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current_move', full_name='gambit.ExecuteMatchResponse.ExecuteMatchState.current_move', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='game_state', full_name='gambit.ExecuteMatchResponse.ExecuteMatchState.game_state', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=390,
  serialized_end=496,
)

_EXECUTEMATCHRESPONSE = _descriptor.Descriptor(
  name='ExecuteMatchResponse',
  full_name='gambit.ExecuteMatchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='match_state', full_name='gambit.ExecuteMatchResponse.match_state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EXECUTEMATCHRESPONSE_EXECUTEMATCHSTATE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=496,
)


_IDENTITYCONFIG = _descriptor.Descriptor(
  name='IdentityConfig',
  full_name='gambit.IdentityConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_token', full_name='gambit.IdentityConfig.client_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=536,
)


_GAMECONFIG = _descriptor.Descriptor(
  name='GameConfig',
  full_name='gambit.GameConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_id', full_name='gambit.GameConfig.game_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=538,
  serialized_end=567,
)


_GAMESTATE = _descriptor.Descriptor(
  name='GameState',
  full_name='gambit.GameState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=569,
  serialized_end=580,
)


_MOVE = _descriptor.Descriptor(
  name='Move',
  full_name='gambit.Move',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=582,
  serialized_end=588,
)

_EXECUTEMATCHREQUEST_CLIENTINIT.fields_by_name['identity'].message_type = _IDENTITYCONFIG
_EXECUTEMATCHREQUEST_CLIENTINIT.fields_by_name['game_config'].message_type = _GAMECONFIG
_EXECUTEMATCHREQUEST_CLIENTINIT.containing_type = _EXECUTEMATCHREQUEST
_EXECUTEMATCHREQUEST_MAKEMOVE.fields_by_name['move'].message_type = _MOVE
_EXECUTEMATCHREQUEST_MAKEMOVE.containing_type = _EXECUTEMATCHREQUEST
_EXECUTEMATCHREQUEST.fields_by_name['init'].message_type = _EXECUTEMATCHREQUEST_CLIENTINIT
_EXECUTEMATCHREQUEST.fields_by_name['make_move'].message_type = _EXECUTEMATCHREQUEST_MAKEMOVE
_EXECUTEMATCHRESPONSE_EXECUTEMATCHSTATE.fields_by_name['game_state'].message_type = _GAMESTATE
_EXECUTEMATCHRESPONSE_EXECUTEMATCHSTATE.containing_type = _EXECUTEMATCHRESPONSE
_EXECUTEMATCHRESPONSE.fields_by_name['match_state'].message_type = _EXECUTEMATCHRESPONSE_EXECUTEMATCHSTATE
DESCRIPTOR.message_types_by_name['ExecuteMatchRequest'] = _EXECUTEMATCHREQUEST
DESCRIPTOR.message_types_by_name['ExecuteMatchResponse'] = _EXECUTEMATCHRESPONSE
DESCRIPTOR.message_types_by_name['IdentityConfig'] = _IDENTITYCONFIG
DESCRIPTOR.message_types_by_name['GameConfig'] = _GAMECONFIG
DESCRIPTOR.message_types_by_name['GameState'] = _GAMESTATE
DESCRIPTOR.message_types_by_name['Move'] = _MOVE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExecuteMatchRequest = _reflection.GeneratedProtocolMessageType('ExecuteMatchRequest', (_message.Message,), dict(

  ClientInit = _reflection.GeneratedProtocolMessageType('ClientInit', (_message.Message,), dict(
    DESCRIPTOR = _EXECUTEMATCHREQUEST_CLIENTINIT,
    __module__ = 'gambit_pb2'
    # @@protoc_insertion_point(class_scope:gambit.ExecuteMatchRequest.ClientInit)
    ))
  ,

  MakeMove = _reflection.GeneratedProtocolMessageType('MakeMove', (_message.Message,), dict(
    DESCRIPTOR = _EXECUTEMATCHREQUEST_MAKEMOVE,
    __module__ = 'gambit_pb2'
    # @@protoc_insertion_point(class_scope:gambit.ExecuteMatchRequest.MakeMove)
    ))
  ,
  DESCRIPTOR = _EXECUTEMATCHREQUEST,
  __module__ = 'gambit_pb2'
  # @@protoc_insertion_point(class_scope:gambit.ExecuteMatchRequest)
  ))
_sym_db.RegisterMessage(ExecuteMatchRequest)
_sym_db.RegisterMessage(ExecuteMatchRequest.ClientInit)
_sym_db.RegisterMessage(ExecuteMatchRequest.MakeMove)

ExecuteMatchResponse = _reflection.GeneratedProtocolMessageType('ExecuteMatchResponse', (_message.Message,), dict(

  ExecuteMatchState = _reflection.GeneratedProtocolMessageType('ExecuteMatchState', (_message.Message,), dict(
    DESCRIPTOR = _EXECUTEMATCHRESPONSE_EXECUTEMATCHSTATE,
    __module__ = 'gambit_pb2'
    # @@protoc_insertion_point(class_scope:gambit.ExecuteMatchResponse.ExecuteMatchState)
    ))
  ,
  DESCRIPTOR = _EXECUTEMATCHRESPONSE,
  __module__ = 'gambit_pb2'
  # @@protoc_insertion_point(class_scope:gambit.ExecuteMatchResponse)
  ))
_sym_db.RegisterMessage(ExecuteMatchResponse)
_sym_db.RegisterMessage(ExecuteMatchResponse.ExecuteMatchState)

IdentityConfig = _reflection.GeneratedProtocolMessageType('IdentityConfig', (_message.Message,), dict(
  DESCRIPTOR = _IDENTITYCONFIG,
  __module__ = 'gambit_pb2'
  # @@protoc_insertion_point(class_scope:gambit.IdentityConfig)
  ))
_sym_db.RegisterMessage(IdentityConfig)

GameConfig = _reflection.GeneratedProtocolMessageType('GameConfig', (_message.Message,), dict(
  DESCRIPTOR = _GAMECONFIG,
  __module__ = 'gambit_pb2'
  # @@protoc_insertion_point(class_scope:gambit.GameConfig)
  ))
_sym_db.RegisterMessage(GameConfig)

GameState = _reflection.GeneratedProtocolMessageType('GameState', (_message.Message,), dict(
  DESCRIPTOR = _GAMESTATE,
  __module__ = 'gambit_pb2'
  # @@protoc_insertion_point(class_scope:gambit.GameState)
  ))
_sym_db.RegisterMessage(GameState)

Move = _reflection.GeneratedProtocolMessageType('Move', (_message.Message,), dict(
  DESCRIPTOR = _MOVE,
  __module__ = 'gambit_pb2'
  # @@protoc_insertion_point(class_scope:gambit.Move)
  ))
_sym_db.RegisterMessage(Move)



_GAMESERVICE = _descriptor.ServiceDescriptor(
  name='GameService',
  full_name='gambit.GameService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=590,
  serialized_end=684,
  methods=[
  _descriptor.MethodDescriptor(
    name='ExecuteMatch',
    full_name='gambit.GameService.ExecuteMatch',
    index=0,
    containing_service=None,
    input_type=_EXECUTEMATCHREQUEST,
    output_type=_EXECUTEMATCHRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GAMESERVICE)

DESCRIPTOR.services_by_name['GameService'] = _GAMESERVICE

# @@protoc_insertion_point(module_scope)
